/* ----------------------------------------------------------------------------
 * File: DialogScatterPlot.java
 * Date: July 3rd, 2013
 * ----------------------------------------------------------------------------
 */
package stats.gui.dialogs;

import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JDialog;
import stats.core.Array;
import stats.core.Node;
import stats.core.Table;

/**
 *
 * @author marco
 */
public class DialogScatterPlot extends JDialog {

  private Node node;

  /**
   * Creates new form DialogScatterPlot
   */
  public DialogScatterPlot(Node node, Frame parent, boolean modal) {

    super(parent, modal);
    
    
    // assign node for source data to the dialog
    if (node == null) throw new IllegalArgumentException(
              "Cannot initialize a DialogScatterPlot without source node.");
    this.node = node;

    // initialize components
    initComponents();
    initComboTables();
    
    setLocationRelativeTo(parent);
  }

  private void initComboTables() {

    for (int i = 0; i < node.getTableNumber(); i++)
      comboTables.addItem(node.getTable(i).name());

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelTable = new javax.swing.JLabel();
    comboTables = new javax.swing.JComboBox();
    splitPane = new javax.swing.JSplitPane();
    jTabbedPane1 = new javax.swing.JTabbedPane();
    panelVariables = new javax.swing.JPanel();
    selectorResponse = new stats.gui.ArraySelector();
    selectorFactor = new stats.gui.ArraySelector();
    selectorGrouping = new stats.gui.ArraySelector();
    selectorSplitting = new stats.gui.ArraySelector();
    panelSettings = new javax.swing.JPanel();
    selectorColumns = new stats.gui.ArraySelector();
    separator = new javax.swing.JSeparator();
    buttonOk = new javax.swing.JButton();
    buttonCancel = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Scatter plot");
    setIconImage(null);

    labelTable.setText("Table:");

    comboTables.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comboTablesActionPerformed(evt);
      }
    });

    splitPane.setDividerLocation(150);

    selectorResponse.setDataType(stats.core.DataTypes.NUMERIC);
    selectorResponse.setSourceSelector(selectorColumns);
    selectorResponse.setTitle("Y, Response variable(s)");

    selectorFactor.setDataType(stats.core.DataTypes.NUMERIC);
    selectorFactor.setSourceSelector(selectorColumns);
    selectorFactor.setTitle("X, Factor variable(s)");

    selectorGrouping.setSourceSelector(selectorColumns);
    selectorGrouping.setTitle("Grouping variable(s)");

    selectorSplitting.setDataType(stats.core.DataTypes.CHARACTER);
    selectorSplitting.setSourceSelector(selectorColumns);
    selectorSplitting.setTitle("Splitting variable(s)");

    javax.swing.GroupLayout panelVariablesLayout = new javax.swing.GroupLayout(panelVariables);
    panelVariables.setLayout(panelVariablesLayout);
    panelVariablesLayout.setHorizontalGroup(
      panelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelVariablesLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(panelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(selectorResponse, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
          .addComponent(selectorFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
          .addComponent(selectorGrouping, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
          .addComponent(selectorSplitting, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        .addContainerGap())
    );
    panelVariablesLayout.setVerticalGroup(
      panelVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panelVariablesLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(selectorResponse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(selectorFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(selectorGrouping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(selectorSplitting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(30, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Variables", panelVariables);

    javax.swing.GroupLayout panelSettingsLayout = new javax.swing.GroupLayout(panelSettings);
    panelSettings.setLayout(panelSettingsLayout);
    panelSettingsLayout.setHorizontalGroup(
      panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 335, Short.MAX_VALUE)
    );
    panelSettingsLayout.setVerticalGroup(
      panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 476, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Options", panelSettings);

    splitPane.setRightComponent(jTabbedPane1);

    selectorColumns.setTitle("Columns");
    splitPane.setLeftComponent(selectorColumns);

    buttonOk.setText("OK");

    buttonCancel.setText("Cancel");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
          .addComponent(separator)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(labelTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboTables, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCancel)))
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(labelTable)
          .addComponent(comboTables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(splitPane)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(buttonOk)
          .addComponent(buttonCancel))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void comboTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTablesActionPerformed

    // identify selected table
    int index = comboTables.getSelectedIndex();
    Table table = node.getTable(index);

    // generate a list of table columns 
    ArrayList<Array> columns = new ArrayList<>();
    for (int i = 0; i < table.columns(); i++)
      columns.add(table.getArray(i));
    // clear column selector and insert table columns
    selectorColumns.clear();
    selectorColumns.insertArrays(columns);

  }//GEN-LAST:event_comboTablesActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonCancel;
  private javax.swing.JButton buttonOk;
  private javax.swing.JComboBox comboTables;
  private javax.swing.JTabbedPane jTabbedPane1;
  private javax.swing.JLabel labelTable;
  private javax.swing.JPanel panelSettings;
  private javax.swing.JPanel panelVariables;
  private stats.gui.ArraySelector selectorColumns;
  private stats.gui.ArraySelector selectorFactor;
  private stats.gui.ArraySelector selectorGrouping;
  private stats.gui.ArraySelector selectorResponse;
  private stats.gui.ArraySelector selectorSplitting;
  private javax.swing.JSeparator separator;
  private javax.swing.JSplitPane splitPane;
  // End of variables declaration//GEN-END:variables

}
