/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stats.gui.dialogs;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author marco
 */
public class DialogInsertRows extends javax.swing.JDialog {

  public static final int POSITION_AFTER = 1;

  public static final int POSITION_BEFORE = 2;

  public static final int POSITION_BEGIN = 3;

  public static final int POSITION_END = 4;

  private boolean dialog_result;

  /**
   * Creates new form DialogInsertRows
   */
  public DialogInsertRows(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    dialog_result = false;        
  }

  public int getRowNumber() {
    return Integer.parseInt(spinner_number.getValue().toString());
  }

  public int getRowPosition() {
    // check which radio button is selected and returns the proper value
    if (radio_after.isSelected()) return POSITION_AFTER;
    else if (radio_before.isSelected()) return POSITION_BEFORE;
    else if (radio_begin.isSelected()) return POSITION_BEGIN;
    else return POSITION_END;
  }

  public boolean showDialog() {
    setVisible(true);
    return dialog_result;
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup = new javax.swing.ButtonGroup();
    label_number = new javax.swing.JLabel();
    spinner_number = new javax.swing.JSpinner();
    javax.swing.JLabel label_position = new javax.swing.JLabel();
    radio_after = new javax.swing.JRadioButton();
    radio_before = new javax.swing.JRadioButton();
    radio_begin = new javax.swing.JRadioButton();
    radio_end = new javax.swing.JRadioButton();
    separator = new javax.swing.JSeparator();
    button_cancel = new javax.swing.JButton();
    button_ok = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Insert rows...");

    label_number.setText("Number:");

    spinner_number.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

    label_position.setText("Position :");

    buttonGroup.add(radio_after);
    radio_after.setSelected(true);
    radio_after.setText("after");

    buttonGroup.add(radio_before);
    radio_before.setText("before");

    buttonGroup.add(radio_begin);
    radio_begin.setText("begin");

    buttonGroup.add(radio_end);
    radio_end.setText("end");

    button_cancel.setText("Cancel");
    button_cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_cancelActionPerformed(evt);
      }
    });

    button_ok.setText("OK");
    button_ok.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button_okActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(label_number)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(spinner_number, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(label_position)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(radio_after)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(radio_before)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(radio_begin)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(radio_end))
          .addComponent(separator)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(button_ok)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(button_cancel)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(label_number)
          .addComponent(spinner_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(radio_before)
          .addComponent(radio_after)
          .addComponent(radio_begin)
          .addComponent(radio_end)
          .addComponent(label_position))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(5, 5, 5)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(button_cancel)
          .addComponent(button_ok))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
    dialog_result = false;
    this.dispose();
  }//GEN-LAST:event_button_cancelActionPerformed

  private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
    dialog_result = true;
    this.dispose();
  }//GEN-LAST:event_button_okActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup;
  private javax.swing.JButton button_cancel;
  private javax.swing.JButton button_ok;
  private javax.swing.JLabel label_number;
  private javax.swing.JRadioButton radio_after;
  private javax.swing.JRadioButton radio_before;
  private javax.swing.JRadioButton radio_begin;
  private javax.swing.JRadioButton radio_end;
  private javax.swing.JSeparator separator;
  private javax.swing.JSpinner spinner_number;
  // End of variables declaration//GEN-END:variables
}
